apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: monitoring
spec:
  type: NodePort
  ports:
  - targetPort: 3000
    port: 3000
    nodePort: 30300
  selector:
    app.kubernetes.io/instance: prometheus-k8s
    app.kubernetes.io/name: grafana
