apiVersion: v1
kind: Service
metadata:
  name: nextgame-monitoring-service
  namespace: nextgame-bot
  labels:
    app: nextgame-bot
spec:
  type: ClusterIP
  ports:
  - name: metrics 
    targetPort: 8000
    port: 8000
  selector:
    app: nextgame-bot
