apiVersion: v1
kind: Service
metadata:
  name: prom-service
  namespace: monitoring
spec:
  type: NodePort
  ports:
  - targetPort: 9090
    port: 9090
    nodePort: 30909
  selector:
    app.kubernetes.io/name: prometheus
    prometheus: prometheus-k8s-kube-promet-prometheus
