apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaresolverr-deployment
  namespace: nextgame-bot
  labels:
    app: flaresolverr
spec:
  template:
    metadata:
      name: flaresolverr
      labels:
        app: flaresolverr
    spec:
      containers:
      - name: flaresolverr
        image: ghcr.io/flaresolverr/flaresolverr:latest
  replicas: 1
  selector:
    matchLabels:
      app: flaresolverr